In [37]:
import os, codecs
import pandas as pd
from pandas.api.types import CategoricalDtype

In [38]:
data_folder = ''
df= pd.read_csv(os.path.join(data_folder,"El_Maestro_for_wrangling.csv"), sep=";")

In [39]:
df.head()

,Número absoluto,Tomo,Número,día,mes como aparece,mes,año,Texto traducido,autor,author_gender,...,posición en la revista,página inicio,inicio percentaje,página final,extensión,largo número,apunte largo,índice,publicidad,precio
0,1,I,1,1.0,abril,4.0,1921,Una declaración de independencia intelectual,Romain Rolland,0.0,...,"pp. 11-12, segunda posición",11.0,NaN,12.0,2.0,96,96 numeradas. Hay una hoja antes (portada+suma...,"sí, sumario al principio, sin números de páginas",no,no mencionado
1,1,I,1,1.0,abril,4.0,1921,El trabajo y la teoría de Bondareff,Leon Tolstoi,0.0,...,pp. 41-53,41.0,NaN,53.0,13.0,96,96 numeradas. Hay una hoja antes (portada+suma...,"sí, sumario al principio, sin números de páginas",no,no mencionado
2,1,I,1,1.0,abril,4.0,1921,El espanto ruso,Bernard Shaw,0.0,...,pp. 54-58,54.0,NaN,58.0,5.0,96,96 numeradas. Hay una hoja antes (portada+suma...,"sí, sumario al principio, sin números de páginas",no,no mencionado
3,1,I,1,1.0,abril,4.0,1921,Fabulas de Esopo,Esopo,0.0,...,p. 94,94.0,NaN,94.0,1.0,96,96 numeradas. Hay una hoja antes (portada+suma...,"sí, sumario al principio, sin números de páginas",no,no mencionado
4,2,I,2,1.0,mayo,5.0,1921,Historia Universal,William Swinton,0.0,...,pp. 21-26,21.0,NaN,26.0,6.0,112,"112 numeradas, con una hoja al principio (port...","sí, sumario al principio, sin números de páginas",no,no mencionado

In [40]:
df.shape

(71, 30)

In [41]:
df.dtypes

Número absoluto               object
Tomo                          object
Número                        object
día                          float64
mes como aparece              object
mes                          float64
año                            int64
Texto traducido               object
autor                         object
author_gender                float64
clasificación/género          object
nacionalidad autor            object
idioma del que se traduce     object
idioma original               object
fecha primera publicación     object
información autor             object
author date of birth         float64
author date of death         float64
traductor                     object
translator_gender            float64
posición en la revista        object
página inicio                float64
inicio percentaje            float64
página final                 float64
extensión                    float64
largo número                   int64
apunte largo                  object
índice                        object
publicidad                    object
precio                        object
dtype: object

In [42]:
df["signature_type"]=df["traductor"] #creating a new signature_type column

In [43]:
df.signature_type.replace(to_replace="anónimo, pero sí se menciona que se trata de una traducción",
                value="anonymous identified", inplace =True)
df.signature_type.replace(to_replace ="anónimo, no se menciona que se trata de una traducción", 
                 value ="anonymous unidentified", inplace=True) 

cat_type = CategoricalDtype(
    categories=["anonymous identified", "anonymous unidentified", "signed"],
    ordered=True
)

df.signature_type = df.signature_type.astype(cat_type) #the signature_type can correspond to three categories: anonymous idenfitied, anonymous unidentified and signed

In [44]:
df.signature_type.fillna('signed',inplace=True) #the missing values (where the name of individual translators appeared previously) are replaced by the "signed" category

In [45]:
df.traductor.replace(to_replace="anónimo, pero sí se menciona que se trata de una traducción",
                value="anon", inplace =True)
df.traductor.replace(to_replace ="anónimo, no se menciona que se trata de una traducción", 
                 value ="anon", inplace=True) #signature types replaced in the traductor column

In [46]:
df[["traductor", "signature_type"]]

   traductor          signature_type
0       anon  anonymous unidentified
1       anon  anonymous unidentified
2       anon  anonymous unidentified
3       anon  anonymous unidentified
4       anon  anonymous unidentified
..       ...                     ...
66       NaN                  signed
67       NaN                  signed
68      anon  anonymous unidentified
69      anon  anonymous unidentified
70       NaN                  signed

[71 rows x 2 columns]